//! Writes the crate's shortcode table, `src/gemoji.rs`, from github/gemoji's
//! `db/emoji.json` and `LICENSE` at a pinned tag:
//!
//! ```text
//! cargo run --manifest-path tools/gemoji/Cargo.toml -- \
//!     emoji.json LICENSE v4.1.0 src/gemoji.rs
//! ```
//!
//! The table holds every name and alias with its emoji, sorted by name so the
//! library looks a name up by binary search, and is headed by gemoji's
//! version and MIT notice.

use std::{env, fmt::Write as _, fs, process::ExitCode};

use serde_json::Value;

fn main() -> ExitCode {
    let args: Vec<String> = env::args().skip(1).collect();
    let [emoji, license, tag, output] = args.as_slice() else {
        eprintln!("usage: gemoji-table <emoji.json> <LICENSE> <tag> <output.rs>");
        return ExitCode::FAILURE;
    };
    match generate(emoji, license, tag) {
        Ok(table) => match fs::write(output, table) {
            Ok(()) => ExitCode::SUCCESS,
            Err(error) => {
                eprintln!("{output}: {error}");
                ExitCode::FAILURE
            }
        },
        Err(error) => {
            eprintln!("{error}");
            ExitCode::FAILURE
        }
    }
}

fn generate(emoji: &str, license: &str, tag: &str) -> Result<String, String> {
    let database = fs::read_to_string(emoji).map_err(|error| format!("{emoji}: {error}"))?;
    let license = fs::read_to_string(license).map_err(|error| format!("{license}: {error}"))?;
    let database: Value =
        serde_json::from_str(&database).map_err(|error| format!("{emoji}: {error}"))?;
    let entries = database
        .as_array()
        .ok_or_else(|| format!("{emoji}: not an array"))?;

    let mut shortcodes: Vec<(String, String)> = Vec::new();
    for entry in entries {
        // Custom entries carry no Unicode emoji, so no glyph to give.
        let Some(glyph) = entry.get("emoji").and_then(Value::as_str) else {
            continue;
        };
        let aliases = entry
            .get("aliases")
            .and_then(Value::as_array)
            .ok_or_else(|| format!("{emoji}: an entry without aliases"))?;
        for alias in aliases {
            let name = alias
                .as_str()
                .ok_or_else(|| format!("{emoji}: an alias that is not a string"))?;
            shortcodes.push((name.to_owned(), glyph.to_owned()));
        }
    }
    shortcodes.sort();
    if let Some(pair) = shortcodes.windows(2).find(|pair| pair[0].0 == pair[1].0) {
        return Err(format!("{emoji}: the name {:?} appears twice", pair[0].0));
    }

    let mut table = String::new();
    let _ = writeln!(
        table,
        "//! The shortcode table: every name and alias in github/gemoji {tag}'s\n\
         //! `db/emoji.json` with its emoji, sorted by name. Generated by\n\
         //! `tools/gemoji`; regenerate it rather than editing it.\n\
         //!\n\
         //! gemoji is under the MIT license:\n\
         //!"
    );
    for line in license.trim_end().lines() {
        if line.is_empty() {
            table.push_str("//!\n");
        } else {
            let _ = writeln!(table, "//! {line}");
        }
    }
    let _ = writeln!(
        table,
        "\n/// Every gemoji name and alias with its emoji, sorted by name.\n\
         static SHORTCODES: [(&str, &str); {}] = [",
        shortcodes.len()
    );
    for (name, glyph) in &shortcodes {
        let _ = writeln!(table, "    ({name:?}, \"{}\"),", escaped(glyph));
    }
    table.push_str(
        "];\n\n\
         /// The emoji gemoji gives `name`.\n\
         pub(crate) fn glyph(name: &str) -> Option<&'static str> {\n    \
         SHORTCODES\n        \
         .binary_search_by(|(entry, _)| (*entry).cmp(name))\n        \
         .ok()\n        \
         .map(|at| SHORTCODES[at].1)\n\
         }\n",
    );
    Ok(table)
}

/// `glyph` with every non-ASCII char written as a `\u{…}` escape, so the
/// table shows variation selectors and joiners.
fn escaped(glyph: &str) -> String {
    glyph
        .chars()
        .map(|char| {
            if char.is_ascii() && !char.is_ascii_control() && char != '"' && char != '\\' {
                char.to_string()
            } else {
                format!("\\u{{{:X}}}", char as u32)
            }
        })
        .collect()
}
