//! The conformance cases whose expected HTML differs from this crate's,
//! each with its reason: `(file, case, reason)`. The report prints a listed
//! case that starts passing apart from an unlisted case that fails.

/// Cases that differ by design: the oracle reads them under another dialect.
pub const DEVIATIONS: &[(&str, usize, &str)] = &[
    ("commonmark/autolink.cases", 11, "a literal autolink forms inside the `<…>` the oracle reads as text"),
    ("commonmark/autolink.cases", 18, "a literal autolink forms inside the `<…>` the oracle reads as text"),
    ("commonmark/autolink.cases", 21, "literal autolinks are part of the syntax; the oracle reads this without them"),
    ("commonmark/autolink.cases", 22, "literal autolinks are part of the syntax; the oracle reads this without them"),
    ("commonmark/autolink.cases", 33, "a literal autolink forms inside the `<…>` the oracle reads as text"),
    ("commonmark/autolink.cases", 36, "a literal autolink forms inside the `<…>` the oracle reads as text"),
    ("commonmark/autolink.cases", 39, "a literal autolink forms inside the `<…>` the oracle reads as text"),
    ("commonmark/code_indented.cases", 19, "indented code is part of the syntax; the oracle turns it off"),
    ("commonmark/code_indented.cases", 23, "indented code is part of the syntax; the oracle turns it off"),
    ("commonmark/commonmark.cases", 96, "frontmatter is part of the syntax; the oracle reads the leading `---` lines as breaks and a heading"),
    ("commonmark/commonmark.cases", 98, "frontmatter is part of the syntax; the oracle reads the leading `---` lines as breaks and a heading"),
    ("commonmark/commonmark.cases", 548, "wiki links are part of the syntax and win over link and reference syntax"),
    ("commonmark/commonmark.cases", 559, "wiki links are part of the syntax and win over link and reference syntax"),
    ("commonmark/commonmark.cases", 590, "wiki links are part of the syntax and win over link and reference syntax"),
    ("commonmark/commonmark.cases", 602, "a literal autolink forms inside the `<…>` the oracle reads as text"),
    ("commonmark/commonmark.cases", 608, "a literal autolink forms inside the `<…>` the oracle reads as text"),
    ("commonmark/commonmark.cases", 611, "literal autolinks are part of the syntax; the oracle reads this without them"),
    ("commonmark/commonmark.cases", 612, "literal autolinks are part of the syntax; the oracle reads this without them"),
    ("commonmark/frontmatter.cases", 1, "frontmatter is part of the syntax; the oracle reads the leading `---` lines as breaks and a heading"),
    ("commonmark/gfm_autolink_literal.cases", 1, "literal autolinks are part of the syntax; the oracle reads this without them"),
    ("commonmark/gfm_autolink_literal.cases", 2, "literal autolinks are part of the syntax; the oracle reads this without them"),
    ("commonmark/gfm_autolink_literal.cases", 3, "literal autolinks are part of the syntax; the oracle reads this without them"),
    ("commonmark/gfm_strikethrough.cases", 2, "strikethrough takes two tildes; the oracle reads one as strikethrough"),
    ("commonmark/gfm_strikethrough.cases", 7, "strikethrough takes two tildes; the oracle reads one as strikethrough"),
    ("commonmark/gfm_strikethrough.cases", 8, "strikethrough takes two tildes; the oracle reads one as strikethrough"),
    ("commonmark/gfm_strikethrough.cases", 9, "strikethrough takes two tildes; the oracle reads one as strikethrough"),
    ("commonmark/gfm_strikethrough.cases", 10, "strikethrough takes two tildes; the oracle reads one as strikethrough"),
    ("commonmark/gfm_strikethrough.cases", 11, "strikethrough takes two tildes; the oracle reads one as strikethrough"),
    ("commonmark/gfm_strikethrough.cases", 12, "strikethrough takes two tildes; the oracle reads one as strikethrough"),
    ("commonmark/gfm_strikethrough.cases", 13, "strikethrough takes two tildes; the oracle reads one as strikethrough"),
    ("commonmark/gfm_strikethrough.cases", 14, "`~~` strikethrough is part of the syntax; the CommonMark oracle reads it as text"),
    ("commonmark/gfm_strikethrough.cases", 16, "strikethrough takes two tildes; the oracle reads one as strikethrough"),
    ("commonmark/gfm_table.cases", 1, "tables are part of the syntax; the oracle reads the rows as text"),
    ("commonmark/gfm_table.cases", 33, "indented code is part of the syntax; the oracle turns it off"),
    ("commonmark/gfm_table.cases", 51, "indented code is part of the syntax; the oracle turns it off"),
    ("commonmark/gfm_tagfilter.cases", 6, "literal autolinks are part of the syntax; the oracle reads this without them"),
    ("commonmark/gfm_task_list_item.cases", 1, "task list items are part of the syntax; the oracle reads `[x]` as text"),
    ("commonmark/heading_setext.cases", 26, "frontmatter is part of the syntax; the oracle reads the leading `---` lines as breaks and a heading"),
    ("commonmark/heading_setext.cases", 28, "frontmatter is part of the syntax; the oracle reads the leading `---` lines as breaks and a heading"),
    ("commonmark/html_flow.cases", 3, "raw HTML blocks are part of the syntax; the oracle turns them off"),
    ("commonmark/image.cases", 20, "wiki links are part of the syntax and win over link and reference syntax"),
    ("commonmark/link_reference.cases", 22, "wiki links are part of the syntax and win over link and reference syntax"),
    ("commonmark/link_reference.cases", 32, "wiki links are part of the syntax and win over link and reference syntax"),
    ("gfm/autolink.cases", 20, "wiki links are part of the syntax and win over link and reference syntax"),
    ("gfm/autolink.cases", 21, "wiki links are part of the syntax and win over link and reference syntax"),
    ("gfm/autolink.cases", 26, "literal autolinks take the strict GFM extents; the oracle uses comrak's relaxed autolinks"),
    ("gfm/autolink.cases", 31, "literal autolinks take the strict GFM extents; the oracle uses comrak's relaxed autolinks"),
    ("gfm/autolink.cases", 32, "literal autolinks take the strict GFM extents; the oracle uses comrak's relaxed autolinks"),
    ("gfm/autolink.cases", 35, "literal autolinks take the strict GFM extents; the oracle uses comrak's relaxed autolinks"),
    ("gfm/autolink.cases", 36, "literal autolinks take the strict GFM extents; the oracle uses comrak's relaxed autolinks"),
    ("gfm/autolink.cases", 37, "literal autolinks take the strict GFM extents; the oracle uses comrak's relaxed autolinks"),
    ("gfm/autolink.cases", 44, "literal autolinks take the strict GFM extents; the oracle uses comrak's relaxed autolinks"),
    ("gfm/autolink.cases", 45, "literal autolinks take the strict GFM extents; the oracle uses comrak's relaxed autolinks"),
    ("gfm/autolink.cases", 54, "wiki links take the title after the pipe; the oracle takes it before"),
    ("gfm/autolink.cases", 57, "literal autolinks take the strict GFM extents; the oracle uses comrak's relaxed autolinks"),
    ("gfm/autolink.cases", 59, "literal autolinks take the strict GFM extents; the oracle uses comrak's relaxed autolinks"),
    ("gfm/autolink.cases", 61, "literal autolinks take the strict GFM extents; the oracle uses comrak's relaxed autolinks"),
    ("gfm/footnotes.cases", 4, "superscript is not part of the syntax; the oracle reads `^2^` as superscript"),
    ("gfm/inline_footnotes.cases", 10, "inline footnotes are part of the syntax; the oracle runs without footnotes"),
    ("gfm/math.cases", 19, "`$$` opens a math block; the GFM oracle reads it as inline display math"),
    ("gfm/math.cases", 23, "`$$` opens a math block; the GFM oracle reads it as inline display math"),
    ("gfm/math.cases", 36, "`$$` opens a math block; the GFM oracle reads it as inline display math"),
    ("gfm/strikethrough.cases", 1, "strikethrough takes two tildes; the oracle reads one as strikethrough"),
    ("gfm/wikilinks.cases", 2, "wiki links take the title after the pipe; the oracle takes it before"),
    ("gfm/wikilinks.cases", 4, "wiki links take the title after the pipe; the oracle takes it before"),
    ("gfm/wikilinks.cases", 6, "wiki links take the title after the pipe; the oracle takes it before"),
];

/// Cases that fail as parser defects, not by design.
pub const KNOWN_DEFECTS: &[(&str, usize, &str)] = &[
    ("commonmark/code_fenced.cases", 35, "fails on main too: should support an eof in the prefix, in content"),
    ("commonmark/fuzz.cases", 8, "fails on main too: 6-a: container close after unclosed fenced code, with eol (block quote, GH-16)"),
    ("commonmark/fuzz.cases", 9, "fails on main too: 6-b: container close after unclosed fenced code, with eol (list, GH-16)"),
    ("commonmark/list.cases", 85, "fails on main too: should remove indent of code (fenced) in list (3 spaces)"),
    ("commonmark/list.cases", 86, "fails on main too: should remove indent of code (fenced) in list (4 spaces)"),
    ("commonmark/list.cases", 87, "fails on main too: should remove indent of code (fenced) in list (1 tab)"),
    ("gfm/autolink.cases", 15, "fails on main too: autolink_ignore_links_in_brackets[0]"),
    ("gfm/autolink.cases", 16, "fails on main too: autolink_ignore_links_in_brackets[1]"),
    ("gfm/autolink.cases", 17, "fails on main too: autolink_ignore_links_in_brackets[2]"),
];
